
name: check platform

on:
  schedule:    
    - cron: "*/5 * * * *"
  
jobs:
  call:
    runs-on: ubuntu-latest
    env:
      CHANNEL_URL: ${{ secrets.SLACK_URL }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm i
    - run: node index.js
